### ISSUE TITLE
How to import it into KorGE?

### ISSUE THREAD

**Issue by VladoCC** [korlibs/luak#2]
I'm tryingto do that `dependencyMulti("com.soywiz", "korlibs.luak","0.3.2-SNAPSHOT")`, butit doesn't work.
Seems that this project can't be foundin standard repos of korge

**Comment by soywiz** [comment]
That's the wrong group and artifact ids. Please, check this file:
https://github.com/korlibs/korge-samples/blob/8ef957b086bf218aad13859d0f08aa10b3cae52d/luak/build.gradle.kts#L7
