### ISSUE TITLE
Maven central publication and examples?

### ISSUE THREAD

**Issue by MrManiacc** [korlibs/luak#3]
Hi I was wondering where I could find a wiki and or the maven dependency. I'd rather not have to build it my self, and go through the code to find examples. Looks like a promising project though

**Comment by soywiz** [comment]
The binaries are published here: https://bintray.com/korlibs/korlibs/luak
I have requested jcenter sync

**Comment by soywiz** [comment]
It has been for some time on central: https://repo.maven.apache.org/maven2/com/soywiz/korlibs/luak/
Closing this
