### ISSUE TITLE
Class found in top-level directory breaks in JDK9+

### ISSUE THREAD

**Issue by cereda** [korlibs/luak#4]
Hi friends! :wink: 

Unfortunately, the lone `lua` class found in the top-level directory causes the library to break in JDK9 and later versions:

```
> Task :cli:run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for /home/paulo/.gradle/caches/modules-2/files-2.1/com.soywiz.korlibs.luak/luak-jvm/2.4.12/f6b6773d80cb262c2b5f861c77cf0a20f93ec69f/luak-jvm-2.4.12.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: lua.class found in top-level directory (unnamed package not allowed in module)
```

Inspecting the resulting library `.jar`, we can find two entries: `lua` and `luac`. Judging by the names, we suspect they come from the Android sources (`jvmAndroidMain`).

Thanks a lot!

**Comment by soywiz** [comment]
No worries my friend, package refactor to he rescue!
* https://github.com/korlibs/luak/commit/fa2089a5f9800794714b779c353f83a85e8e0def
* https://github.com/korlibs/luak/releases/tag/v2.4.13
* https://github.com/korlibs/luak/actions/runs/2186356151

**Comment by cereda** [comment]
Hi Carlos!

Wow, this is awesome! Thanks so much for the prompt reply and action! We really appreciate it! :tada: 

Muchas gracias, amigo! :heart:

**Comment by soywiz** [comment]
Não há de que parceiro!
